### ISSUE TITLE
Question about nvblox_interface target

### ISSUE THREAD

**Issue by rencheckyoself** [nvidia-isaac/nvblox#19]
Hi! 

I am using your library but needed a ROS1 interface so I converted the `isaac_ros_nvblox/nvblox_ros` package to `noetic`. Everything is working good now, but I got stuck for the longest time sorting out an issue where I couldn't use the CUDA implementation to extract the ESDF as a Pointcloud. The issue came from using to the wrong target when linking the `nvblox` library with my new `nvblox_ros` package. 

Initially, I was linking against the targets `nvblox_lib` and `nvblox_eigen`, following the ROS2 `CMakeLists.txt`, but switching those out in favor of `nvblox_interface` fixed the issue. The comments here mention this target it specifically meant for ROS, but that its also been marked to be deleted: https://github.com/nvidia-isaac/nvblox/blob/public/nvblox/CMakeLists.txt#L199.

I was just hoping to get some additional context for the `nvblox_interface` target, like why it was needed originally, and now is it only needed now for ROS1 since its not being used in the `isaac_ros_nvblox` package? I was doing some reading up on the INTERFACE keyword, so I guess it has something to do with how `nvblox`, `stdgpu`, and `eigen` libraries are made, but I still don't actually understand why using `nvblox_lib` caused the issue.

I appreciate any details you're willing to provide, thanks!

**Comment by hsurya08** [comment]
Hi @rencheckyoself,

I am trying to use the nvblox package with ROS noetic as well. Could you please help me out if you were able to get it running successfully. Thanks!

**Comment by rencheckyoself** [comment]
Yea, I got everything running. I just converted the `isaac_ros_nvblox/nvblox_ros` (a different repository that uses this repository) package from ROS2 syntax to ROS1 syntax. Just make sure you link against the `nvblox_interface` for the files that depend on this repo. 

Though I haven't tried with the newest version of `nvblox` they recently released yet.

**Comment by alexmillane** [comment]
There's this repo here: https://github.com/leggedrobotics/glimpse_nvblox_ros1

It's a fork for nvblox_ros for ROS1. It's a year old version, and I haven't tried it so I don't know how well it works. But maybe you could get some clues on how they did it by looking at the code.

**Comment by hsurya08** [comment]
> Yea, I got everything running. I just converted the `isaac_ros_nvblox/nvblox_ros` (a different repository that uses this repository) package from ROS2 syntax to ROS1 syntax. Just make sure you link against the `nvblox_interface` for the files that depend on this repo.
> 
> Though I haven't tried with the newest version of `nvblox` they recently released yet.

Hi @rencheckyoself, thanks for the reply. It is great to know that you were able to use it with ROS1. I am also using the ROS2 interface package isaac_ros_nvblox, so I guess I should be able to convert it to ROS1. Thanks again!

**Comment by hsurya08** [comment]
> There's this repo here: https://github.com/leggedrobotics/glimpse_nvblox_ros1
> 
> It's a fork for nvblox_ros for ROS1. It's a year old version, and I haven't tried it so I don't know how well it works. But maybe you could get some clues on how they did it by looking at the code.

Hi @alexmillane, the repository seems to be promising. I was actually looking for something like this for reference and this is really helpful. I will update you once I test it. Thanks!
