### ISSUE TITLE
build error in cuda 12.1

### ISSUE THREAD

**Issue by zhangzscn** [nvidia-isaac/nvblox#25]
[build] [  5%] Built target ext_eigen
[build] [  5%] Building CXX object _deps/ext_stdgpu-build/src/stdgpu/CMakeFiles/stdgpu.dir/impl/iterator.cpp.o
[build] [  6%] Building CXX object _deps/ext_stdgpu-build/src/stdgpu/CMakeFiles/stdgpu.dir/impl/memory.cpp.o
[build] [  6%] Building CXX object _deps/ext_stdgpu-build/src/stdgpu/CMakeFiles/stdgpu.dir/impl/limits.cpp.o
[build] [  7%] Building CXX object _deps/ext_stdgpu-build/src/stdgpu/CMakeFiles/stdgpu.dir/cuda/impl/memory.cpp.o
[build] [  7%] Linking CXX static library libstdgpu.a
[build] [  7%] Built target stdgpu
[build] [  8%] Building CUDA object CMakeFiles/nvblox_gpu_hash.dir/src/core/error_check.cu.o
[build] [  8%] Building CXX object CMakeFiles/nvblox_gpu_hash.dir/src/utils/timing.cpp.o
[build] [  9%] Building CXX object CMakeFiles/nvblox_gpu_hash.dir/src/utils/nvtx_ranges.cpp.o
[build] [ 10%] Building CUDA object CMakeFiles/nvblox_gpu_hash.dir/src/gpu_hash/gpu_layer_view.cu.o
[build] [ 10%] Building CUDA object CMakeFiles/nvblox_gpu_hash.dir/src/gpu_hash/gpu_set.cu.o
[build] [ 11%] Linking CXX static library libnvblox_gpu_hash.a
[build] [ 11%] Built target nvblox_gpu_hash
[build] [ 11%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/core/warmup.cu.o
[build] [ 12%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/core/error_check.cu.o
[build] [ 12%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/map/blox.cu.o
[build] [ 13%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/map/layer.cu.o
[build] [ 14%] Building CXX object CMakeFiles/nvblox_lib.dir/src/sensors/camera.cpp.o
[build] [ 14%] Building CXX object CMakeFiles/nvblox_lib.dir/src/sensors/color.cpp.o
[build] [ 15%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/sensors/pointcloud.cu.o
[build] [ 15%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/sensors/image.cu.o
[build] [ 15%] Building CXX object CMakeFiles/nvblox_lib.dir/src/geometry/bounding_spheres.cpp.o
[build] [ 16%] Building CXX object CMakeFiles/nvblox_lib.dir/src/mapper/mapper.cpp.o
[build] [ 17%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/integrators/view_calculator.cu.o
[build] [ 18%] Building CXX object CMakeFiles/nvblox_lib.dir/src/geometry/bounding_boxes.cpp.o
[build] [ 19%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/integrators/occupancy_decay_integrator.cu.o
[build] [ 19%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/integrators/projective_occupancy_integrator.cu.o
[build] [ 19%] Building CXX object CMakeFiles/nvblox_lib.dir/src/mapper/multi_mapper.cpp.o
[build] [ 20%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/integrators/esdf_integrator.cu.o
[build] [ 20%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/rays/sphere_tracer.cu.o
[build] [ 22%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/integrators/projective_tsdf_integrator.cu.o
[build] [ 22%] Building CXX object CMakeFiles/nvblox_lib.dir/src/interpolation/interpolation_3d.cpp.o
[build] [ 22%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/integrators/projective_color_integrator.cu.o
[build] [ 23%] Building CXX object CMakeFiles/nvblox_lib.dir/src/io/mesh_io.cpp.o
[build] [ 24%] Building CXX object CMakeFiles/nvblox_lib.dir/src/io/layer_cake_io.cpp.o
[build] [ 24%] Building CXX object CMakeFiles/nvblox_lib.dir/src/io/ply_writer.cpp.o
[build] [ 24%] Building CXX object CMakeFiles/nvblox_lib.dir/src/io/pointcloud_io.cpp.o
[build] [ 25%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/mesh/mesh_integrator_color.cu.o
[build] [ 25%] Building CXX object CMakeFiles/nvblox_lib.dir/src/io/image_io.cpp.o
[build] [ 25%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/mesh/marching_cubes.cu.o
[build] [ 26%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/mesh/mesh_block.cu.o
[build] [ 27%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/mesh/mesh_integrator.cu.o
[build] [ 28%] Building CXX object CMakeFiles/nvblox_lib.dir/src/mesh/mesh.cpp.o
[build] [ 29%] Building CXX object CMakeFiles/nvblox_lib.dir/src/primitives/scene.cpp.o
[build] [ 29%] Building CXX object CMakeFiles/nvblox_lib.dir/src/primitives/primitives.cpp.o
[build] [ 29%] Building CXX object CMakeFiles/nvblox_lib.dir/src/utils/nvtx_ranges.cpp.o
[build] [ 30%] Building CXX object CMakeFiles/nvblox_lib.dir/src/utils/timing.cpp.o
[build] [ 30%] Building CXX object CMakeFiles/nvblox_lib.dir/src/serialization/serializer.cpp.o
[build] [ 31%] Building CXX object CMakeFiles/nvblox_lib.dir/src/serialization/sqlite_database.cpp.o
[build] [ 32%] Building CXX object CMakeFiles/nvblox_lib.dir/src/serialization/layer_type_register.cpp.o
[build] [ 32%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/semantics/image_masker.cu.o
[build] [ 33%] Building CUDA object CMakeFiles/nvblox_lib.dir/src/semantics/image_projector.cu.o
[build] /mnt/data1/nvblox/nvblox/src/integrators/esdf_integrator.cu(1002): error: qualified name is not allowed
[build]     typedef cub::BlockRadixSort<uint64_t, kBlockThreads, kItemsPerThread,
[build]             ^
[build] 
[build] /mnt/data1/nvblox/nvblox/src/integrators/esdf_integrator.cu(1002): error: expected a ";"
[build]     typedef cub::BlockRadixSort<uint64_t, kBlockThreads, kItemsPerThread,
[build]                                ^
[build] 
[build] /mnt/data1/nvblox/nvblox/src/integrators/esdf_integrator.cu(1011): error: a class or namespace qualified name is required
[build]       typename BlockRadixSortT::TempStorage sort;
[build]                ^
[build] 
[build] /mnt/data1//nvblox/nvblox/src/integrators/esdf_integrator.cu(1011): error: global-scope qualifier (leading "::") is not allowed
[build]       typename BlockRadixSortT::TempStorage sort;
[build]                               ^
[build] 
[build] /mnt/data1//nvblox/nvblox/src/integrators/esdf_integrator.cu(1011): error: expected a ";"
[build]       typename BlockRadixSortT::TempStorage sort;
[build]                                             ^
[build] 
[build] /mnt/data1//nvblox/nvblox/src/integrators/esdf_integrator.cu(1090): error: namespace "thrust" has no member "sort"
[build]       thrust::sort(thrust::device, block_indices->begin(), block_indices->end(),
[build]               ^
[build] 
[build] /mnt/data1//nvblox/nvblox/src/integrators/esdf_integrator.cu(1095): error: namespace "thrust" has no member "unique"
[build]       auto iterator = thrust::unique(thrust::device, block_indices->begin(),
[build]                               ^
[build] 
[build] 7 errors detected in the compilation of "/mnt/data1//nvblox/nvblox/src/integrators/esdf_integrator.cu".

**Comment by alexmillane** [comment]
Could you check if this fixes the issue?

https://github.com/nvidia-isaac/nvblox/pull/26

Thanks :)

**Comment by zhangzscn** [comment]
yes，it work
