### ISSUE TITLE
Is nvblox the GPU version of Voxgraph？

### ISSUE THREAD

**Issue by Janebek** [nvidia-isaac/nvblox#28]
Hi！Thanks for you azamzing work on nvblox!

My question is that is nvblox the GPU version of Voxgraph? If not, what are those changes compared to the Voxgraph?

I'm really looking forward to your reply! Thanks for your time!

**Comment by alexmillane** [comment]
Hi, there. Thanks for your interest. nvblox is the GPU-based successor to vox*blox*.

It doesn't include the global mapping aspects of voxgraph: submapping and global optimization of the map.

The aspects of voxblox/voxgraph that it does do, however, it does much faster.

Hope that sort of answers your question.

**Comment by Janebek** [comment]
Thanks for your reply!
