### ISSUE TITLE
Compatibility of Nvblox with Jetson Xavier NX running Ubuntu 20.04 (ROS Noetic)

### ISSUE THREAD

**Issue by hsurya08** [nvidia-isaac/nvblox#30]
Hi!

Thanks for the great work. I am using the nvblox package on Jetson xavier running on ubuntu 20.4 with ROS noetic. I see that the Nvblox package currently supports ROS2 Humble version. However, I have most of my other related work in ROS noetic and would not be possible to migrate to ROS2 at this point. Moreover, my Jetson xavier has arm64 architecture running on ubuntu 20.04 (Tier 3 platform) which is not a supported platform to install ros2 humble (https://docs.ros.org/en/humble/Releases/Release-Humble-Hawksbill.html#supported-platforms). Therefore, I tried it with ROS2 foxy and was able to get it running on the Jetson using the docker. I was just hoping if there is a way to run the nvblox package with ros noetic version so that I can integrate my existing work to it. 

I appreciate any information you are willing to provide. Thanks!

**Comment by yuliangzhong** [comment]
Hi!

Check this ros1 wrapper.  https://github.com/ethz-asl/nvblox_ros1

Just follow the instructions in readme. It should work, since I tried and succeeded :)

**Comment by alexmillane** [comment]
Thank you for the response @yuliangzhong . I'll close this now :)
