### ISSUE TITLE
Tutorial to build a reconstruction from a realsense camera?

### ISSUE THREAD

**Issue by shivanshpatel35** [nvidia-isaac/nvblox#47]
What tutorial file should we use to build a reconstruction? The README [here](https://github.com/nvidia-isaac/nvblox/blob/public/README.md?plain=1#L59) links to a file which does not exist now.

**Comment by alexmillane** [comment]
https://nvidia-isaac-ros.github.io/concepts/scene_reconstruction/nvblox/tutorials/tutorial_realsense.html
