### ISSUE TITLE
libnvvpi.so.3: undefined symbol: PvaProgramSetDMADescriptorsV2

### ISSUE THREAD

**Issue by shubaozhang** [nvidia-isaac/nvblox#53]
https://nvidia-isaac-ros.github.io/repositories_and_packages/isaac_ros_nvblox/isaac_ros_nvblox/index.html#troubleshooting

ros2 launch nvblox_examples_bringup isaac_sim_example.launch.py \
rosbag:=${ISAAC_ROS_WS}/isaac_ros_assets/isaac_ros_nvblox/quickstart \
navigation:=False

After runing the above example file, the following error happens.

![nvblox_error](https://github.com/user-attachments/assets/c1368717-3622-4e23-bc0f-eb84a68f649a)

**Comment by alexmillane** [comment]
Thank you for reporting the issue. 

Could you describe which platform you're running on and the install steps leading up to this error. Could you also post the full log output here?

Thank you.

**Comment by shubaozhang** [comment]
The problem is due to JetPack version 5.1, as which is required the version 6.
